use std::path::Path;

pub struct LanguageSpec {
    pub name: &'static str,
    pub lsp_id: &'static str,
    pub extensions: &'static [&'static str],
    pub keywords: &'static [&'static str],
    pub types: &'static [&'static str],
    pub line_comment: Option<&'static str>,
    pub block_comment: Option<(&'static str, &'static str)>,
    pub nested_block_comments: bool,
    pub string_delims: &'static [char],
    pub multiline_string_delims: &'static [char],
    pub char_literal: bool,
    pub uppercase_types: bool,
    pub macro_bang: bool,
    pub colon_indent: bool,
}

pub fn detect(path: Option<&Path>) -> Option<&'static LanguageSpec> {
    let ext = path?.extension()?.to_str()?.to_ascii_lowercase();
    LANGUAGES
        .iter()
        .find(|spec| spec.extensions.contains(&ext.as_str()))
}

const DEFAULTS: LanguageSpec = LanguageSpec {
    name: "",
    lsp_id: "",
    extensions: &[],
    keywords: &[],
    types: &[],
    line_comment: None,
    block_comment: None,
    nested_block_comments: false,
    string_delims: &['"'],
    multiline_string_delims: &[],
    char_literal: false,
    uppercase_types: false,
    macro_bang: false,
    colon_indent: false,
};

pub static LANGUAGES: &[LanguageSpec] = &[
    LanguageSpec {
        name: "Rust",
        lsp_id: "rust",
        extensions: &["rs"],
        keywords: &[
            "as", "async", "await", "break", "const", "continue", "crate", "dyn", "else", "enum",
            "extern", "false", "fn", "for", "if", "impl", "in", "let", "loop", "match", "mod",
            "move", "mut", "pub", "ref", "return", "self", "static", "struct", "super", "trait",
            "true", "type", "union", "unsafe", "use", "where", "while",
        ],
        types: &[
            "bool", "char", "str", "i8", "i16", "i32", "i64", "i128", "isize", "u8", "u16", "u32",
            "u64", "u128", "usize", "f32", "f64", "Self", "String", "Vec", "Option", "Result",
            "Box",
        ],
        line_comment: Some("//"),
        block_comment: Some(("/*", "*/")),
        nested_block_comments: true,
        string_delims: &['"'],
        multiline_string_delims: &['"'],
        char_literal: true,
        uppercase_types: true,
        macro_bang: true,
        colon_indent: false,
    },
    LanguageSpec {
        name: "TOML",
        lsp_id: "toml",
        extensions: &["toml"],
        keywords: &["true", "false"],
        line_comment: Some("#"),
        string_delims: &['"', '\''],
        ..DEFAULTS
    },
    LanguageSpec {
        name: "Python",
        lsp_id: "python",
        extensions: &["py"],
        keywords: &[
            "and", "as", "assert", "async", "await", "break", "case", "class", "continue", "def",
            "del", "elif", "else", "except", "finally", "for", "from", "global", "if", "import",
            "in", "is", "lambda", "match", "nonlocal", "not", "or", "pass", "raise", "return",
            "try", "while", "with", "yield", "True", "False", "None",
        ],
        types: &[
            "int", "float", "str", "bool", "list", "dict", "set", "tuple", "bytes", "object",
        ],
        line_comment: Some("#"),
        string_delims: &['"', '\''],
        uppercase_types: true,
        colon_indent: true,
        ..DEFAULTS
    },
    LanguageSpec {
        name: "JavaScript",
        lsp_id: "javascript",
        extensions: &["js", "mjs", "cjs", "jsx"],
        keywords: JS_KEYWORDS,
        line_comment: Some("//"),
        block_comment: Some(("/*", "*/")),
        string_delims: &['"', '\'', '`'],
        multiline_string_delims: &['`'],
        uppercase_types: true,
        ..DEFAULTS
    },
    LanguageSpec {
        name: "TypeScript",
        lsp_id: "typescript",
        extensions: &["ts", "tsx"],
        keywords: TS_KEYWORDS,
        types: &[
            "string", "number", "boolean", "object", "symbol", "bigint", "void", "any", "unknown",
            "never",
        ],
        line_comment: Some("//"),
        block_comment: Some(("/*", "*/")),
        string_delims: &['"', '\'', '`'],
        multiline_string_delims: &['`'],
        uppercase_types: true,
        ..DEFAULTS
    },
    LanguageSpec {
        name: "C",
        lsp_id: "c",
        extensions: &["c", "h"],
        keywords: C_KEYWORDS,
        types: C_TYPES,
        line_comment: Some("//"),
        block_comment: Some(("/*", "*/")),
        char_literal: true,
        uppercase_types: true,
        ..DEFAULTS
    },
    LanguageSpec {
        name: "C++",
        lsp_id: "cpp",
        extensions: &["cpp", "cc", "cxx", "hpp", "hh", "hxx"],
        keywords: CPP_KEYWORDS,
        types: C_TYPES,
        line_comment: Some("//"),
        block_comment: Some(("/*", "*/")),
        char_literal: true,
        uppercase_types: true,
        ..DEFAULTS
    },
    LanguageSpec {
        name: "Go",
        lsp_id: "go",
        extensions: &["go"],
        keywords: &[
            "break",
            "case",
            "chan",
            "const",
            "continue",
            "default",
            "defer",
            "else",
            "fallthrough",
            "for",
            "func",
            "go",
            "goto",
            "if",
            "import",
            "interface",
            "map",
            "package",
            "range",
            "return",
            "select",
            "struct",
            "switch",
            "type",
            "var",
            "true",
            "false",
            "nil",
            "iota",
        ],
        types: &[
            "any",
            "bool",
            "byte",
            "complex64",
            "complex128",
            "error",
            "float32",
            "float64",
            "int",
            "int8",
            "int16",
            "int32",
            "int64",
            "rune",
            "string",
            "uint",
            "uint8",
            "uint16",
            "uint32",
            "uint64",
            "uintptr",
        ],
        line_comment: Some("//"),
        block_comment: Some(("/*", "*/")),
        string_delims: &['"', '`'],
        multiline_string_delims: &['`'],
        char_literal: true,
        uppercase_types: true,
        ..DEFAULTS
    },
    LanguageSpec {
        name: "Shell",
        lsp_id: "shellscript",
        extensions: &["sh", "bash", "zsh"],
        keywords: &[
            "if", "then", "else", "elif", "fi", "for", "while", "until", "do", "done", "case",
            "esac", "function", "in", "select", "return", "exit", "local", "export", "readonly",
            "declare", "source", "break", "continue",
        ],
        line_comment: Some("#"),
        string_delims: &['"', '\''],
        ..DEFAULTS
    },
    LanguageSpec {
        name: "JSON",
        lsp_id: "json",
        extensions: &["json"],
        keywords: &["true", "false", "null"],
        ..DEFAULTS
    },
    LanguageSpec {
        name: "YAML",
        lsp_id: "yaml",
        extensions: &["yml", "yaml"],
        keywords: &["true", "false", "null", "yes", "no"],
        line_comment: Some("#"),
        string_delims: &['"', '\''],
        ..DEFAULTS
    },
];

const JS_KEYWORDS: &[&str] = &[
    "async",
    "await",
    "break",
    "case",
    "catch",
    "class",
    "const",
    "continue",
    "debugger",
    "default",
    "delete",
    "do",
    "else",
    "export",
    "extends",
    "finally",
    "for",
    "function",
    "if",
    "import",
    "in",
    "instanceof",
    "let",
    "new",
    "null",
    "of",
    "return",
    "static",
    "super",
    "switch",
    "this",
    "throw",
    "true",
    "try",
    "typeof",
    "undefined",
    "var",
    "void",
    "while",
    "with",
    "yield",
];

const TS_KEYWORDS: &[&str] = &[
    "abstract",
    "any",
    "as",
    "async",
    "await",
    "break",
    "case",
    "catch",
    "class",
    "const",
    "continue",
    "debugger",
    "declare",
    "default",
    "delete",
    "do",
    "else",
    "enum",
    "export",
    "extends",
    "finally",
    "for",
    "function",
    "if",
    "implements",
    "import",
    "in",
    "instanceof",
    "interface",
    "is",
    "keyof",
    "let",
    "namespace",
    "never",
    "new",
    "null",
    "of",
    "private",
    "protected",
    "public",
    "readonly",
    "return",
    "satisfies",
    "static",
    "super",
    "switch",
    "this",
    "throw",
    "true",
    "try",
    "type",
    "typeof",
    "undefined",
    "unknown",
    "var",
    "void",
    "while",
    "with",
    "yield",
];

const C_KEYWORDS: &[&str] = &[
    "auto", "break", "case", "const", "continue", "default", "do", "else", "enum", "extern", "for",
    "goto", "if", "inline", "register", "restrict", "return", "sizeof", "static", "struct",
    "switch", "typedef", "union", "volatile", "while", "true", "false", "NULL",
];

const CPP_KEYWORDS: &[&str] = &[
    "auto",
    "break",
    "case",
    "catch",
    "class",
    "const",
    "constexpr",
    "const_cast",
    "continue",
    "default",
    "delete",
    "do",
    "dynamic_cast",
    "else",
    "enum",
    "explicit",
    "extern",
    "final",
    "for",
    "friend",
    "goto",
    "if",
    "inline",
    "mutable",
    "namespace",
    "new",
    "noexcept",
    "nullptr",
    "operator",
    "override",
    "private",
    "protected",
    "public",
    "register",
    "reinterpret_cast",
    "return",
    "sizeof",
    "static",
    "static_cast",
    "struct",
    "switch",
    "template",
    "this",
    "throw",
    "try",
    "typedef",
    "typename",
    "union",
    "using",
    "virtual",
    "volatile",
    "while",
    "true",
    "false",
    "NULL",
];

const C_TYPES: &[&str] = &[
    "void", "char", "short", "int", "long", "float", "double", "signed", "unsigned", "bool",
    "size_t", "ssize_t", "int8_t", "int16_t", "int32_t", "int64_t", "uint8_t", "uint16_t",
    "uint32_t", "uint64_t",
];
