use std::path::Path;
use std::sync::RwLock;

pub struct LanguageSpec {
    pub name: &'static str,
    pub lsp_id: &'static str,
    pub extensions: &'static [&'static str],
    pub filenames: &'static [&'static str],
    pub keywords: &'static [&'static str],
    pub types: &'static [&'static str],
    pub line_comment: Option<&'static str>,
    pub block_comment: Option<(&'static str, &'static str)>,
    pub nested_block_comments: bool,
    pub string_delims: &'static [char],
    pub multiline_string_delims: &'static [char],
    pub triple_quote_delims: &'static [char],
    pub char_literal: bool,
    pub uppercase_types: bool,
    pub macro_bang: bool,
    pub colon_indent: bool,
    pub case_insensitive_keywords: bool,
    pub markdown: bool,
}

/// Languages registered at runtime by plugins. Checked before the built-ins so a
/// plugin can override one.
static EXTRA: RwLock<Vec<&'static LanguageSpec>> = RwLock::new(Vec::new());

pub fn detect(path: Option<&Path>) -> Option<&'static LanguageSpec> {
    let path = path?;
    let name = path.file_name()?.to_str()?.to_ascii_lowercase();
    let ext = path
        .extension()
        .and_then(|e| e.to_str())
        .map(str::to_ascii_lowercase);
    let matches = |spec: &LanguageSpec| {
        spec.filenames.contains(&name.as_str())
            || ext.as_deref().is_some_and(|e| spec.extensions.contains(&e))
    };
    if let Ok(extra) = EXTRA.read() {
        if let Some(spec) = extra.iter().copied().find(|spec| matches(spec)) {
            return Some(spec);
        }
    }
    BUILTIN.iter().find(|spec| matches(spec))
}

/// Every known language, plugin-registered first. Allocates, so use it for
/// listings only -- `detect` is on the per-keystroke path.
pub fn languages() -> Vec<&'static LanguageSpec> {
    let mut all: Vec<&'static LanguageSpec> = match EXTRA.read() {
        Ok(extra) => extra.iter().copied().collect(),
        Err(_) => Vec::new(),
    };
    all.extend(BUILTIN.iter());
    all
}

/// Owned mirror of `LanguageSpec`, for languages that arrive at runtime.
#[derive(Default)]
pub struct LanguageDef {
    pub name: String,
    pub lsp_id: String,
    pub extensions: Vec<String>,
    pub filenames: Vec<String>,
    pub keywords: Vec<String>,
    pub types: Vec<String>,
    pub line_comment: Option<String>,
    pub block_comment: Option<(String, String)>,
    pub nested_block_comments: bool,
    pub string_delims: Vec<char>,
    pub multiline_string_delims: Vec<char>,
    pub triple_quote_delims: Vec<char>,
    pub char_literal: bool,
    pub uppercase_types: bool,
    pub macro_bang: bool,
    pub colon_indent: bool,
    pub case_insensitive_keywords: bool,
}

pub fn register(def: LanguageDef) -> Result<(), String> {
    if def.name.trim().is_empty() {
        return Err("language name must not be empty".to_string());
    }
    if def.extensions.is_empty() && def.filenames.is_empty() {
        return Err(format!(
            "language `{}` needs at least one extension or filename",
            def.name
        ));
    }
    let keywords = if def.case_insensitive_keywords {
        lowercase(def.keywords)
    } else {
        def.keywords
    };
    // ponytail: leaked, never freed -- plugins load once at startup and never
    // unload, so this beats making every LanguageSpec field owned.
    let spec: &'static LanguageSpec = Box::leak(Box::new(LanguageSpec {
        name: leak_str(def.name),
        lsp_id: leak_str(def.lsp_id),
        extensions: leak_strs(lowercase(def.extensions)),
        filenames: leak_strs(lowercase(def.filenames)),
        keywords: leak_strs(keywords),
        types: leak_strs(def.types),
        line_comment: def.line_comment.map(leak_str),
        block_comment: def
            .block_comment
            .map(|(open, close)| (leak_str(open), leak_str(close))),
        nested_block_comments: def.nested_block_comments,
        string_delims: leak_chars(def.string_delims),
        multiline_string_delims: leak_chars(def.multiline_string_delims),
        triple_quote_delims: leak_chars(def.triple_quote_delims),
        char_literal: def.char_literal,
        uppercase_types: def.uppercase_types,
        macro_bang: def.macro_bang,
        colon_indent: def.colon_indent,
        case_insensitive_keywords: def.case_insensitive_keywords,
        markdown: false,
    }));
    EXTRA
        .write()
        .map_err(|_| "language registry is poisoned".to_string())?
        .push(spec);
    Ok(())
}

fn lowercase(values: Vec<String>) -> Vec<String> {
    values
        .into_iter()
        .map(|value| value.to_ascii_lowercase())
        .collect()
}

fn leak_str(value: String) -> &'static str {
    Box::leak(value.into_boxed_str())
}

fn leak_strs(values: Vec<String>) -> &'static [&'static str] {
    let leaked: Vec<&'static str> = values.into_iter().map(leak_str).collect();
    Box::leak(leaked.into_boxed_slice())
}

fn leak_chars(values: Vec<char>) -> &'static [char] {
    Box::leak(values.into_boxed_slice())
}

const DEFAULTS: LanguageSpec = LanguageSpec {
    name: "",
    lsp_id: "",
    extensions: &[],
    filenames: &[],
    keywords: &[],
    types: &[],
    line_comment: None,
    block_comment: None,
    nested_block_comments: false,
    string_delims: &['"'],
    multiline_string_delims: &[],
    triple_quote_delims: &[],
    char_literal: false,
    uppercase_types: false,
    macro_bang: false,
    colon_indent: false,
    case_insensitive_keywords: false,
    markdown: false,
};

static BUILTIN: &[LanguageSpec] = &[
    LanguageSpec {
        name: "Rust",
        lsp_id: "rust",
        extensions: &["rs"],
        keywords: &[
            "as", "async", "await", "break", "const", "continue", "crate", "dyn", "else", "enum",
            "extern", "false", "fn", "for", "if", "impl", "in", "let", "loop", "match", "mod",
            "move", "mut", "pub", "ref", "return", "self", "static", "struct", "super", "trait",
            "true", "type", "union", "unsafe", "use", "where", "while",
        ],
        types: &[
            "bool", "char", "str", "i8", "i16", "i32", "i64", "i128", "isize", "u8", "u16", "u32",
            "u64", "u128", "usize", "f32", "f64", "Self", "String", "Vec", "Option", "Result",
            "Box",
        ],
        line_comment: Some("//"),
        block_comment: Some(("/*", "*/")),
        nested_block_comments: true,
        multiline_string_delims: &['"'],
        char_literal: true,
        uppercase_types: true,
        macro_bang: true,
        ..DEFAULTS
    },
    LanguageSpec {
        name: "TOML",
        lsp_id: "toml",
        extensions: &["toml"],
        keywords: &["true", "false"],
        line_comment: Some("#"),
        string_delims: &['"', '\''],
        ..DEFAULTS
    },
    LanguageSpec {
        name: "Python",
        lsp_id: "python",
        extensions: &["py", "pyi", "pyw"],
        keywords: &[
            "and", "as", "assert", "async", "await", "break", "case", "class", "continue", "def",
            "del", "elif", "else", "except", "finally", "for", "from", "global", "if", "import",
            "in", "is", "lambda", "match", "nonlocal", "not", "or", "pass", "raise", "return",
            "try", "while", "with", "yield", "True", "False", "None",
        ],
        types: &[
            "int", "float", "str", "bool", "list", "dict", "set", "tuple", "bytes", "object",
        ],
        line_comment: Some("#"),
        string_delims: &['"', '\''],
        triple_quote_delims: &['"', '\''],
        uppercase_types: true,
        colon_indent: true,
        ..DEFAULTS
    },
    LanguageSpec {
        name: "JavaScript",
        lsp_id: "javascript",
        extensions: &["js", "mjs", "cjs", "jsx"],
        keywords: JS_KEYWORDS,
        line_comment: Some("//"),
        block_comment: Some(("/*", "*/")),
        string_delims: &['"', '\'', '`'],
        multiline_string_delims: &['`'],
        uppercase_types: true,
        ..DEFAULTS
    },
    LanguageSpec {
        name: "TypeScript",
        lsp_id: "typescript",
        extensions: &["ts", "tsx", "mts", "cts"],
        keywords: TS_KEYWORDS,
        types: &[
            "string", "number", "boolean", "object", "symbol", "bigint", "void", "any", "unknown",
            "never",
        ],
        line_comment: Some("//"),
        block_comment: Some(("/*", "*/")),
        string_delims: &['"', '\'', '`'],
        multiline_string_delims: &['`'],
        uppercase_types: true,
        ..DEFAULTS
    },
    LanguageSpec {
        name: "C",
        lsp_id: "c",
        extensions: &["c", "h"],
        keywords: C_KEYWORDS,
        types: C_TYPES,
        line_comment: Some("//"),
        block_comment: Some(("/*", "*/")),
        char_literal: true,
        uppercase_types: true,
        ..DEFAULTS
    },
    LanguageSpec {
        name: "C++",
        lsp_id: "cpp",
        extensions: &["cpp", "cc", "cxx", "hpp", "hh", "hxx"],
        keywords: CPP_KEYWORDS,
        types: C_TYPES,
        line_comment: Some("//"),
        block_comment: Some(("/*", "*/")),
        char_literal: true,
        uppercase_types: true,
        ..DEFAULTS
    },
    LanguageSpec {
        name: "Go",
        lsp_id: "go",
        extensions: &["go"],
        keywords: &[
            "break",
            "case",
            "chan",
            "const",
            "continue",
            "default",
            "defer",
            "else",
            "fallthrough",
            "for",
            "func",
            "go",
            "goto",
            "if",
            "import",
            "interface",
            "map",
            "package",
            "range",
            "return",
            "select",
            "struct",
            "switch",
            "type",
            "var",
            "true",
            "false",
            "nil",
            "iota",
        ],
        types: &[
            "any",
            "bool",
            "byte",
            "complex64",
            "complex128",
            "error",
            "float32",
            "float64",
            "int",
            "int8",
            "int16",
            "int32",
            "int64",
            "rune",
            "string",
            "uint",
            "uint8",
            "uint16",
            "uint32",
            "uint64",
            "uintptr",
        ],
        line_comment: Some("//"),
        block_comment: Some(("/*", "*/")),
        string_delims: &['"', '`'],
        multiline_string_delims: &['`'],
        char_literal: true,
        uppercase_types: true,
        ..DEFAULTS
    },
    LanguageSpec {
        name: "Shell",
        lsp_id: "shellscript",
        extensions: &["sh", "bash", "zsh"],
        // ponytail: no heredocs -- the delim model is single-char.
        filenames: &[
            ".bashrc",
            ".bash_profile",
            ".bash_aliases",
            ".profile",
            ".zshrc",
            ".zshenv",
            ".zprofile",
        ],
        keywords: &[
            "if", "then", "else", "elif", "fi", "for", "while", "until", "do", "done", "case",
            "esac", "function", "in", "select", "return", "exit", "local", "export", "readonly",
            "declare", "source", "break", "continue",
        ],
        line_comment: Some("#"),
        string_delims: &['"', '\''],
        ..DEFAULTS
    },
    LanguageSpec {
        name: "JSON",
        lsp_id: "json",
        extensions: &["json"],
        keywords: &["true", "false", "null"],
        ..DEFAULTS
    },
    LanguageSpec {
        name: "YAML",
        lsp_id: "yaml",
        extensions: &["yml", "yaml"],
        keywords: &["true", "false", "null", "yes", "no"],
        line_comment: Some("#"),
        string_delims: &['"', '\''],
        ..DEFAULTS
    },
    LanguageSpec {
        name: "Java",
        lsp_id: "java",
        extensions: &["java"],
        keywords: JAVA_KEYWORDS,
        types: JAVA_TYPES,
        line_comment: Some("//"),
        block_comment: Some(("/*", "*/")),
        triple_quote_delims: &['"'],
        char_literal: true,
        uppercase_types: true,
        ..DEFAULTS
    },
    LanguageSpec {
        name: "C#",
        lsp_id: "csharp",
        extensions: &["cs"],
        keywords: CSHARP_KEYWORDS,
        types: CSHARP_TYPES,
        line_comment: Some("//"),
        block_comment: Some(("/*", "*/")),
        triple_quote_delims: &['"'],
        char_literal: true,
        uppercase_types: true,
        ..DEFAULTS
    },
    LanguageSpec {
        name: "Kotlin",
        lsp_id: "kotlin",
        extensions: &["kt", "kts"],
        keywords: KOTLIN_KEYWORDS,
        types: &[
            "Any", "Boolean", "Byte", "Char", "Double", "Float", "Int", "Long", "Nothing", "Short",
            "String", "Unit", "List", "Map", "Set", "Array",
        ],
        line_comment: Some("//"),
        block_comment: Some(("/*", "*/")),
        nested_block_comments: true,
        triple_quote_delims: &['"'],
        char_literal: true,
        uppercase_types: true,
        ..DEFAULTS
    },
    LanguageSpec {
        name: "Swift",
        lsp_id: "swift",
        extensions: &["swift"],
        keywords: SWIFT_KEYWORDS,
        types: &[
            "Any",
            "Bool",
            "Character",
            "Double",
            "Float",
            "Int",
            "Int8",
            "Int16",
            "Int32",
            "Int64",
            "String",
            "UInt",
            "UInt8",
            "UInt16",
            "UInt32",
            "UInt64",
            "Void",
            "Array",
            "Dictionary",
            "Optional",
            "Set",
            "Result",
        ],
        line_comment: Some("//"),
        block_comment: Some(("/*", "*/")),
        nested_block_comments: true,
        triple_quote_delims: &['"'],
        uppercase_types: true,
        ..DEFAULTS
    },
    LanguageSpec {
        name: "Ruby",
        lsp_id: "ruby",
        extensions: &["rb", "rake", "gemspec", "ru"],
        // ponytail: no heredocs and no =begin/=end block comments.
        filenames: &[
            "gemfile",
            "rakefile",
            "guardfile",
            "podfile",
            "brewfile",
            "vagrantfile",
        ],
        keywords: RUBY_KEYWORDS,
        line_comment: Some("#"),
        string_delims: &['"', '\'', '`'],
        uppercase_types: true,
        ..DEFAULTS
    },
    LanguageSpec {
        name: "PHP",
        lsp_id: "php",
        extensions: &["php", "phtml"],
        // ponytail: one line_comment slot, so `//` wins and `#` is not marked.
        keywords: PHP_KEYWORDS,
        types: &[
            "bool", "int", "float", "string", "array", "object", "mixed", "void", "never",
            "iterable", "callable", "self", "parent",
        ],
        line_comment: Some("//"),
        block_comment: Some(("/*", "*/")),
        string_delims: &['"', '\''],
        uppercase_types: true,
        ..DEFAULTS
    },
    LanguageSpec {
        name: "Lua",
        lsp_id: "lua",
        extensions: &["lua"],
        // ponytail: no `[[ ]]` long strings -- string delims are single chars.
        keywords: &[
            "and", "break", "do", "else", "elseif", "end", "false", "for", "function", "goto",
            "if", "in", "local", "nil", "not", "or", "repeat", "return", "self", "then", "true",
            "until", "while",
        ],
        line_comment: Some("--"),
        block_comment: Some(("--[[", "]]")),
        string_delims: &['"', '\''],
        ..DEFAULTS
    },
    LanguageSpec {
        name: "SQL",
        lsp_id: "",
        extensions: &["sql"],
        keywords: SQL_KEYWORDS,
        types: SQL_TYPES,
        line_comment: Some("--"),
        block_comment: Some(("/*", "*/")),
        string_delims: &['\'', '"'],
        case_insensitive_keywords: true,
        ..DEFAULTS
    },
    LanguageSpec {
        name: "CSS",
        lsp_id: "css",
        extensions: &["css", "scss", "sass", "less"],
        // ponytail: hyphenated properties can never match (`-` is not an ident
        // char), so these are single words only; `//` is accepted for all four
        // extensions even though plain CSS has no line comment.
        keywords: &[
            "charset",
            "media",
            "import",
            "supports",
            "keyframes",
            "include",
            "mixin",
            "extend",
            "use",
            "forward",
            "function",
            "return",
            "if",
            "else",
            "each",
            "for",
            "while",
            "and",
            "or",
            "not",
            "only",
            "from",
            "to",
            "inherit",
            "initial",
            "unset",
            "revert",
            "none",
            "auto",
            "important",
            "true",
            "false",
            "null",
        ],
        line_comment: Some("//"),
        block_comment: Some(("/*", "*/")),
        string_delims: &['"', '\''],
        ..DEFAULTS
    },
    LanguageSpec {
        name: "HTML",
        lsp_id: "html",
        extensions: &["html", "htm", "xhtml", "xml", "svg"],
        // ponytail: tags highlight because tag names are keywords; attribute
        // values fall out as strings. No <script>/<style> sublexing.
        keywords: HTML_TAGS,
        line_comment: None,
        block_comment: Some(("<!--", "-->")),
        string_delims: &['"', '\''],
        ..DEFAULTS
    },
    LanguageSpec {
        name: "Markdown",
        lsp_id: "",
        extensions: &["md", "markdown"],
        markdown: true,
        ..DEFAULTS
    },
];

const JS_KEYWORDS: &[&str] = &[
    "async",
    "await",
    "break",
    "case",
    "catch",
    "class",
    "const",
    "continue",
    "debugger",
    "default",
    "delete",
    "do",
    "else",
    "export",
    "extends",
    "finally",
    "for",
    "function",
    "if",
    "import",
    "in",
    "instanceof",
    "let",
    "new",
    "null",
    "of",
    "return",
    "static",
    "super",
    "switch",
    "this",
    "throw",
    "true",
    "try",
    "typeof",
    "undefined",
    "var",
    "void",
    "while",
    "with",
    "yield",
];

const TS_KEYWORDS: &[&str] = &[
    "abstract",
    "any",
    "as",
    "async",
    "await",
    "break",
    "case",
    "catch",
    "class",
    "const",
    "continue",
    "debugger",
    "declare",
    "default",
    "delete",
    "do",
    "else",
    "enum",
    "export",
    "extends",
    "finally",
    "for",
    "function",
    "if",
    "implements",
    "import",
    "in",
    "instanceof",
    "interface",
    "is",
    "keyof",
    "let",
    "namespace",
    "never",
    "new",
    "null",
    "of",
    "private",
    "protected",
    "public",
    "readonly",
    "return",
    "satisfies",
    "static",
    "super",
    "switch",
    "this",
    "throw",
    "true",
    "try",
    "type",
    "typeof",
    "undefined",
    "unknown",
    "var",
    "void",
    "while",
    "with",
    "yield",
];

const C_KEYWORDS: &[&str] = &[
    "auto", "break", "case", "const", "continue", "default", "do", "else", "enum", "extern", "for",
    "goto", "if", "inline", "register", "restrict", "return", "sizeof", "static", "struct",
    "switch", "typedef", "union", "volatile", "while", "true", "false", "NULL",
];

const CPP_KEYWORDS: &[&str] = &[
    "auto",
    "break",
    "case",
    "catch",
    "class",
    "const",
    "constexpr",
    "const_cast",
    "continue",
    "default",
    "delete",
    "do",
    "dynamic_cast",
    "else",
    "enum",
    "explicit",
    "extern",
    "final",
    "for",
    "friend",
    "goto",
    "if",
    "inline",
    "mutable",
    "namespace",
    "new",
    "noexcept",
    "nullptr",
    "operator",
    "override",
    "private",
    "protected",
    "public",
    "register",
    "reinterpret_cast",
    "return",
    "sizeof",
    "static",
    "static_cast",
    "struct",
    "switch",
    "template",
    "this",
    "throw",
    "try",
    "typedef",
    "typename",
    "union",
    "using",
    "virtual",
    "volatile",
    "while",
    "true",
    "false",
    "NULL",
];

const C_TYPES: &[&str] = &[
    "void", "char", "short", "int", "long", "float", "double", "signed", "unsigned", "bool",
    "size_t", "ssize_t", "int8_t", "int16_t", "int32_t", "int64_t", "uint8_t", "uint16_t",
    "uint32_t", "uint64_t",
];

const JAVA_KEYWORDS: &[&str] = &[
    "abstract",
    "assert",
    "break",
    "case",
    "catch",
    "class",
    "const",
    "continue",
    "default",
    "do",
    "else",
    "enum",
    "extends",
    "final",
    "finally",
    "for",
    "goto",
    "if",
    "implements",
    "import",
    "instanceof",
    "interface",
    "native",
    "new",
    "package",
    "permits",
    "private",
    "protected",
    "public",
    "record",
    "return",
    "sealed",
    "static",
    "strictfp",
    "super",
    "switch",
    "synchronized",
    "this",
    "throw",
    "throws",
    "transient",
    "try",
    "var",
    "volatile",
    "while",
    "yield",
    "true",
    "false",
    "null",
];

const JAVA_TYPES: &[&str] = &[
    "boolean",
    "byte",
    "char",
    "double",
    "float",
    "int",
    "long",
    "short",
    "void",
    "String",
    "Object",
    "Integer",
    "Long",
    "Double",
    "Boolean",
    "Character",
    "List",
    "Map",
    "Set",
    "Optional",
];

const CSHARP_KEYWORDS: &[&str] = &[
    "abstract",
    "as",
    "async",
    "await",
    "base",
    "break",
    "case",
    "catch",
    "checked",
    "class",
    "const",
    "continue",
    "default",
    "delegate",
    "do",
    "else",
    "enum",
    "event",
    "explicit",
    "extern",
    "finally",
    "fixed",
    "for",
    "foreach",
    "get",
    "goto",
    "if",
    "implicit",
    "in",
    "init",
    "interface",
    "internal",
    "is",
    "lock",
    "namespace",
    "nameof",
    "new",
    "null",
    "operator",
    "out",
    "override",
    "params",
    "partial",
    "private",
    "protected",
    "public",
    "readonly",
    "record",
    "ref",
    "return",
    "sealed",
    "set",
    "sizeof",
    "stackalloc",
    "static",
    "struct",
    "switch",
    "this",
    "throw",
    "true",
    "false",
    "try",
    "typeof",
    "unchecked",
    "unsafe",
    "using",
    "var",
    "virtual",
    "void",
    "volatile",
    "while",
    "yield",
];

const CSHARP_TYPES: &[&str] = &[
    "bool", "byte", "char", "decimal", "double", "dynamic", "float", "int", "long", "object",
    "sbyte", "short", "string", "uint", "ulong", "ushort", "nint", "nuint",
];

const KOTLIN_KEYWORDS: &[&str] = &[
    "as",
    "break",
    "by",
    "class",
    "companion",
    "const",
    "constructor",
    "continue",
    "crossinline",
    "data",
    "do",
    "else",
    "enum",
    "external",
    "false",
    "field",
    "final",
    "finally",
    "for",
    "fun",
    "get",
    "if",
    "import",
    "in",
    "infix",
    "init",
    "inline",
    "inner",
    "interface",
    "internal",
    "is",
    "it",
    "lateinit",
    "lazy",
    "null",
    "object",
    "open",
    "operator",
    "out",
    "override",
    "package",
    "private",
    "protected",
    "public",
    "reified",
    "return",
    "sealed",
    "set",
    "super",
    "suspend",
    "this",
    "throw",
    "true",
    "try",
    "typealias",
    "val",
    "var",
    "vararg",
    "when",
    "where",
    "while",
];

const SWIFT_KEYWORDS: &[&str] = &[
    "actor",
    "as",
    "associatedtype",
    "async",
    "await",
    "break",
    "case",
    "catch",
    "class",
    "continue",
    "defer",
    "deinit",
    "didSet",
    "do",
    "else",
    "enum",
    "extension",
    "fallthrough",
    "false",
    "fileprivate",
    "final",
    "for",
    "func",
    "get",
    "guard",
    "if",
    "import",
    "in",
    "indirect",
    "init",
    "inout",
    "internal",
    "is",
    "lazy",
    "let",
    "mutating",
    "nil",
    "open",
    "operator",
    "private",
    "protocol",
    "public",
    "repeat",
    "rethrows",
    "return",
    "self",
    "set",
    "some",
    "static",
    "struct",
    "subscript",
    "super",
    "switch",
    "throw",
    "throws",
    "true",
    "try",
    "typealias",
    "var",
    "weak",
    "where",
    "while",
    "willSet",
];

const RUBY_KEYWORDS: &[&str] = &[
    "alias",
    "and",
    "attr_accessor",
    "attr_reader",
    "attr_writer",
    "begin",
    "break",
    "case",
    "class",
    "def",
    "do",
    "else",
    "elsif",
    "end",
    "ensure",
    "extend",
    "false",
    "for",
    "if",
    "in",
    "include",
    "lambda",
    "module",
    "next",
    "nil",
    "not",
    "or",
    "proc",
    "redo",
    "require",
    "require_relative",
    "rescue",
    "retry",
    "return",
    "self",
    "super",
    "then",
    "true",
    "undef",
    "unless",
    "until",
    "when",
    "while",
    "yield",
];

const PHP_KEYWORDS: &[&str] = &[
    "abstract",
    "and",
    "array",
    "as",
    "break",
    "callable",
    "case",
    "catch",
    "class",
    "clone",
    "const",
    "continue",
    "declare",
    "default",
    "do",
    "echo",
    "else",
    "elseif",
    "empty",
    "enum",
    "extends",
    "final",
    "finally",
    "fn",
    "for",
    "foreach",
    "function",
    "global",
    "goto",
    "if",
    "implements",
    "include",
    "include_once",
    "instanceof",
    "insteadof",
    "interface",
    "isset",
    "list",
    "match",
    "namespace",
    "new",
    "or",
    "print",
    "private",
    "protected",
    "public",
    "readonly",
    "require",
    "require_once",
    "return",
    "static",
    "switch",
    "throw",
    "trait",
    "try",
    "unset",
    "use",
    "var",
    "while",
    "xor",
    "yield",
    "true",
    "false",
    "null",
];

/// Lowercase: `SQL` sets `case_insensitive_keywords`.
const SQL_KEYWORDS: &[&str] = &[
    "all",
    "alter",
    "and",
    "as",
    "asc",
    "begin",
    "between",
    "by",
    "case",
    "cast",
    "check",
    "coalesce",
    "commit",
    "constraint",
    "create",
    "cross",
    "default",
    "delete",
    "desc",
    "distinct",
    "drop",
    "else",
    "end",
    "exists",
    "foreign",
    "from",
    "full",
    "group",
    "having",
    "in",
    "index",
    "inner",
    "insert",
    "into",
    "is",
    "join",
    "key",
    "left",
    "like",
    "limit",
    "not",
    "null",
    "offset",
    "on",
    "or",
    "order",
    "outer",
    "primary",
    "references",
    "returning",
    "right",
    "rollback",
    "select",
    "set",
    "table",
    "then",
    "transaction",
    "union",
    "unique",
    "update",
    "using",
    "values",
    "view",
    "when",
    "where",
    "with",
];

/// Lowercase: `SQL` sets `case_insensitive_keywords`, which also lowercases the
/// word before the type lookup.
const SQL_TYPES: &[&str] = &[
    "bigint",
    "blob",
    "boolean",
    "char",
    "date",
    "decimal",
    "double",
    "float",
    "int",
    "integer",
    "json",
    "jsonb",
    "numeric",
    "real",
    "serial",
    "smallint",
    "text",
    "time",
    "timestamp",
    "uuid",
    "varchar",
];

const HTML_TAGS: &[&str] = &[
    "a",
    "abbr",
    "article",
    "aside",
    "audio",
    "b",
    "blockquote",
    "body",
    "br",
    "button",
    "canvas",
    "caption",
    "code",
    "col",
    "colgroup",
    "datalist",
    "dd",
    "details",
    "dialog",
    "div",
    "dl",
    "doctype",
    "dt",
    "em",
    "embed",
    "fieldset",
    "figcaption",
    "figure",
    "footer",
    "form",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "head",
    "header",
    "hgroup",
    "hr",
    "html",
    "i",
    "iframe",
    "img",
    "input",
    "ins",
    "kbd",
    "label",
    "legend",
    "li",
    "link",
    "main",
    "mark",
    "menu",
    "meta",
    "nav",
    "noscript",
    "object",
    "ol",
    "optgroup",
    "option",
    "output",
    "p",
    "param",
    "picture",
    "pre",
    "progress",
    "q",
    "s",
    "samp",
    "script",
    "section",
    "select",
    "slot",
    "small",
    "source",
    "span",
    "strong",
    "style",
    "sub",
    "summary",
    "sup",
    "svg",
    "table",
    "tbody",
    "td",
    "template",
    "textarea",
    "tfoot",
    "th",
    "thead",
    "time",
    "title",
    "tr",
    "track",
    "u",
    "ul",
    "use",
    "var",
    "video",
    "wbr",
];
